name: Update Movies

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm install

      - run: node scraper/scraper3.js > scraper/movies.json

      - run: cat scraper/movies.json

      - run: node scraper/enrich.js > scraper/movies.enriched.json

      - run: cat scraper/movies.enriched.json